name: Run Honkai Star Rail Event Scraper

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin transformers torch

      - name: Create service account key file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}' | base64 -d > serviceAccountKey.json
          python -c "import json; print('JSON is valid') if json.load(open('serviceAccountKey.json')) else ''" || echo "Invalid JSON"

      - name: Run scraper
        run: |
          sed -i 's|src/assets/images/events|event-calendar/src/assets/images/events|g' main.py
          sed -i 's|src/assets/images/events/sections|event-calendar/src/assets/images/events/sections|g' main.py
          python main.py
        
      - name: Commit new images
        run: |
          mkdir -p event-calendar/src/assets/images/events/sections
          
          if [ -d "src/assets/images/events" ]; then
            mv src/assets/images/events/* event-calendar/src/assets/images/events/ || true
          fi
          
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add event-calendar/src/assets/images/events/
          git diff --staged --quiet || git commit -m "Update event images [skip ci]"
          git push || echo "No changes to push"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Angular dependencies
        run: |
          cd event-calendar
          npm install
          
      - name: Build Angular app with production config
        run: |
          cd event-calendar
          npm run build -- --configuration=production

      - name: Create firebase.json
        run: |
          cat > firebase.json << EOF
          {
            "hosting": {
              "public": "event-calendar/dist/event-calendar/browser",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }
          EOF

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Clean up service account key
        if: always()
        run: rm -f serviceAccountKey.json