name: Run Honkai Star Rail Event Scraper

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives write permission to repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin transformers torch

      - name: Create service account key file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}' | base64 -d > serviceAccountKey.json
          # Verify the file is valid JSON
          python -c "import json; print('JSON is valid') if json.load(open('serviceAccountKey.json')) else ''" || echo "Invalid JSON"

      - name: Run scraper
        run: |
          # First, modify the script to use the correct path
          sed -i 's|src/assets/images/events|event-calendar/src/assets/images/events|g' main.py
          sed -i 's|src/assets/images/events/sections|event-calendar/src/assets/images/events/sections|g' main.py
          
          # Run the scraper
          python main.py
        
      - name: Commit new images
        run: |
          # Make sure directories exist
          mkdir -p event-calendar/src/assets/images/events/sections
          
          # Move any images that might have been created in the wrong location
          if [ -d "src/assets/images/events" ]; then
            mv src/assets/images/events/* event-calendar/src/assets/images/events/ || true
          fi
          
          # Configure git
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Add all images
          git add event-calendar/src/assets/images/events/
          
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "Update event images [skip ci]"
          git push || echo "No changes to push"

      # Updated to Node.js v20 to be compatible with Firebase CLI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Angular dependencies
        run: |
          cd event-calendar
          npm install
          
      - name: Build Angular app
        run: |
          cd event-calendar
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}'
          channelId: 'live'
          projectId: 'project-ba-eff57'
          entryPoint: './event-calendar'

      - name: Clean up service account key
        if: always()
        run: rm -f serviceAccountKey.json