name: Run Honkai Star Rail Event Scraper

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives write permission to repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin transformers torch

      - name: Create service account key file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}' | base64 -d > serviceAccountKey.json
          # Verify the file is valid JSON
          python -c "import json; print('JSON is valid') if json.load(open('serviceAccountKey.json')) else ''" || echo "Invalid JSON"

      - name: Run scraper
        run: python main.py
        
      - name: Commit new images
        run: |
          # Make sure directories exist
          mkdir -p src/assets/images/events/sections
          
          # Configure git
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Add all images
          git add src/assets/images/events/
          
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "Update event images [skip ci]"
          git push || echo "No changes to push"

      - name: Clean up service account key
        if: always()
        run: rm -f serviceAccountKey.json